{{- $fullName := include "common.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers: {{ toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range .Values.extraEnvs }}
            - name: {{ toString .name }}
              value: {{ toString .value | quote }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- with .Values.ports }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
          {{- with .Values.readinessProbe -}}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
          {{- with .Values.livenessProbe -}}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- range .Values.configmapMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- if .Values.storage.enabled }}
          - name: data
            mountPath: {{ .Values.storage.mountPath }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- range .Values.configmaps }}
        - name: {{ .name }}
          configMap:
            {{- if .configmapName }}
            name: {{ .configmapName }}
            {{- else }}
            name: {{ $fullName }}
            {{- end }}
        {{- end }}
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
            {{- end }}
        {{- end }}
        {{- if .Values.storage.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ $fullName }}
        {{- end }}
        {{- range .Values.storage.extraStorage }}
        - name: {{ toString .name }}
          persistentVolumeClaim:
            claimName: {{ toString .name }}
            readOnly: {{ toString .readOnly }}
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
