apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ toString .name }}
      targetPort: {{ toString .containerPort }}
      port: {{ toString .containerPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
